# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12858997b138042f65b345a99e8209400205fb23ea225ffa6b0d8e222dc267979ee6ea6da4e1ea58490a6b0141dca1cfbb847089bbfa2e2129dd16920aae6b09

test:
  secret_key_base: 197a5e3396d9f474214a1fd28ee5577f906c5616c530d07d536184b99eb74626de4dee4a6628397c530259a0cd8827d3a36d331d05db31c0c304419ebbeda7e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
